### ISSUE TITLE
4. Update Private Member Functionality

### ISSUE THREAD

**Issue by TiyisoWolfiez** [COS214-Project-2024/Team-28#10]
4. Update Private Member Functionality
Add functionality to handle new private members in building types.

**Comment by AntiDope00** [comment]
Added Private Members townhouses, houses and flats in Estate, and added respect numberBuilding() of vector functions to get composition of Estate. Added addHouse(), addTownHouse and addFlat() functions as well

**Comment by AntiDope00** [comment]
done
